name: flutter_signin_button
description: A Flutter plugin for iOS and Android for generating signin buttons for different social media account.
author: Zayn Jarvis <zaynjarvis@gmail.com>
homepage: https://github.com/ZaynJarvis/Flutter-Sign-in-Button
version: 1.0.0

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
#  font_awesome_flutter: ^8.2.0
  line_awesome_icons: ^1.0.4+2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logos/google_light.png
    - assets/logos/google_dark.png
